### ISSUE TITLE
pressure plate crash server

### ISSUE THREAD

**Issue by Trencks** [Kaeios/Nations#5]
if anyone walk on pressure plate with redstone systeme in a claim the server crash

**Comment by Kaeios** [comment]
Hi, thank you for the bug report, I have made a bugfix for that. Does it works with that version for you ?
[NationsUpdated-2.10.1.zip](https://github.com/Kaeios/Nations/files/4471457/NationsUpdated-2.10.1.zip)

**Comment by Trencks** [comment]
Pressure plate was fix ... but now new glitch , button do the same thing and maybe all item work with redstone/stickypiston/piston

**Comment by Trencks** [comment]
and thx for fix this so quick ^^

**Comment by Kaeios** [comment]
Hi, I tried a fix for that in this version
[NationsUpdated-2.10.1.zip](https://github.com/Kaeios/Nations/files/4474193/NationsUpdated-2.10.1.zip)

**Comment by Trencks** [comment]
all work big thx ! 
if you want play pixelmon i just open my new serv pixelmon fr/en and evidently nations is here ^^
so say it and i send you all information ^^
and thx for the quick fix !

**Comment by Kaeios** [comment]
Thank you for opening this issue and testing the bug fixes
