### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Farcenim17** [Kaeios/Nations#7]
Ho,

Yeah so, everytime I modify the config file of Nation Updated, save it and restart my server (the usual manipulation to configure a file) it come back to the old one.

Keeping me away of setting the nation creation price for exemple.

Any idea how to fix that?

Sorry for my kinda bad english, Im french!

**Comment by Kaeios** [comment]
Hi, use the /na reload when in game to reload the config file.

Salut, il est possible de modifier le fichier de config puis de faire **/na reload** en jeu pour recharger la nouvelle configuration. Il est également possible de stopper le serveur, d'éditer le fichier puis le redémarrer.

**Comment by Farcenim17** [comment]
Hi, thank you very much or you fast answer 🙂 

Have à Nice one
