### ISSUE TITLE
Spammed with Notifications

### ISSUE THREAD

**Issue by 14williamsj** [Kaeios/Nations#8]
So just been setting this up on a server and whenever i enter or leave a zone a message pops up on my screen, and also appears in the console, i know that this isn't an error but I've been unable to work out how to stop this. If there is a way could you please let me know.
[message.txt](https://github.com/Kaeios/Nations/files/4664274/message.txt)

**Comment by Kaeios** [comment]
Hi, do you want to remove it only in console or also in the actionbar ?

**Comment by Kaeios** [comment]
I made a version with two new config options

others.logNationEnter - to disable this message in logs
others.enableEnterNotif - to disable the actionbar when you enter/leave a zone

[NationsUpdated-2.10.2.zip](https://github.com/Kaeios/Nations/files/4672539/NationsUpdated-2.10.2.zip)

**Comment by 14williamsj** [comment]
Sorry for the slow reply, thank you so much.
